class RhinoModifyObjectAttributesEventArgs(EventArgs):
 # no doc
 Document=property(lambda self: object(),lambda self,v: None,lambda self: None)
 """Get: Document(self: RhinoModifyObjectAttributesEventArgs) -> RhinoDoc



"""

 NewAttributes=property(lambda self: object(),lambda self,v: None,lambda self: None)
 """Get: NewAttributes(self: RhinoModifyObjectAttributesEventArgs) -> ObjectAttributes



"""

 OldAttributes=property(lambda self: object(),lambda self,v: None,lambda self: None)
 """Get: OldAttributes(self: RhinoModifyObjectAttributesEventArgs) -> ObjectAttributes



"""

 RhinoObject=property(lambda self: object(),lambda self,v: None,lambda self: None)
 """Get: RhinoObject(self: RhinoModifyObjectAttributesEventArgs) -> RhinoObject



"""


